module.exports = {
  CustomMap: require('../dist/vl-mapactions-all.src.js').CustomMap,
  MapWithActions: require('../dist/vl-mapactions-all.src.js').MapWithActions,
  SnapInteraction: require('../dist/vl-mapactions-all.src.js').SnapInteraction,
  BoxSelectAction: require('../dist/vl-mapactions-all.src.js').BoxSelectAction,
  DeleteAction: require('../dist/vl-mapactions-all.src.js').DeleteAction,
  DrawAction: require('../dist/vl-mapactions-all.src.js').DrawAction,
  DrawLijnstukAction: require('../dist/vl-mapactions-all.src.js').DrawLijnstukAction,
  DrawRectangleAction: require('../dist/vl-mapactions-all.src.js').DrawRectangleAction,
  HighlightAction: require('../dist/vl-mapactions-all.src.js').HighlightAction,
  MapAction: require('../dist/vl-mapactions-all.src.js').MapAction,
  MeasureAction: require('../dist/vl-mapactions-all.src.js').MeasureAction,
  ModifyAction: require('../dist/vl-mapactions-all.src.js').ModifyAction,
  ModifyAndTranslateAction: require('../dist/vl-mapactions-all.src.js').ModifyAndTranslateAction,
  SelectAction: require('../dist/vl-mapactions-all.src.js').SelectAction,
  SelectActions: require('../dist/vl-mapactions-all.src.js').SelectActions,
  ShowInfoAction: require('../dist/vl-mapactions-all.src.js').ShowInfoAction,
  ShowInfoSelectAction: require('../dist/vl-mapactions-all.src.js').ShowInfoSelectAction,
  SplitAction: require('../dist/vl-mapactions-all.src.js').SplitAction,
  Tooltips: require('../dist/vl-mapactions-all.src.js').Tooltips,
  TranslateAction: require('../dist/vl-mapactions-all.src.js').TranslateAction
};
